In [ ]:
import pandas as pd
df = pd.read_csv("../files/messy_ecommerce_sales_data.csv")

df

In [3]:
df.head()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.00
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.05
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.51

In [4]:
df.tail()

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,NaN,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [5]:
df.shape

(103, 11)

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    str
 2   Order_ID        103 non-null    str
 3   Order_Date      103 non-null    str
 4   Product         103 non-null    str
 5    Category       95 non-null     str
 6   Quantity        98 non-null     str
 7   Price           98 non-null     str
 8   Payment_Method  103 non-null    str
 9   Status          103 non-null    str
 10  Total           89 non-null     float64
dtypes: float64(1), int64(1), str(9)
memory usage: 9.0 KB

In [7]:
df.describe()

               ID         Total
count  103.000000     89.000000
mean   149.640777   1232.949101
std     28.704326   2605.471455
min    100.000000 -20000.000000
25%    125.500000    582.130000
50%    149.000000   1138.760000
75%    174.500000   2153.400000
max    199.000000   4722.700000

In [8]:
df.sample(5)

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
35,135,Customer_135,ORD-33656,2/9/2025,Smartwatch,electronics,4,446.19,Cash on Delivery,Cancelled,1784.76
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,NaN,978.63,Bank Transfer,Processing,NaN
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.60
86,186,Customer_186,ORD-90569,10/6/2025,Laptop,Electronics,1,365.34,Bank Transfer,Delivered,365.34
47,147,Customer_147,ORD-80707,5/1/2025,Jacket,Clothing,4,596.15,Cash on Delivery,Shipped,2384.60

In [9]:
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          8
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [10]:
(df.isnull().sum() / len(df)) * 100

ID                 0.000000
 Customer_Name     0.000000
Order_ID           0.000000
Order_Date         0.000000
Product            0.000000
 Category          7.766990
Quantity           4.854369
Price              4.854369
Payment_Method     0.000000
Status             0.000000
Total             13.592233
dtype: float64

In [12]:
df[' Category'] = df[' Category'].fillna('Unknown')

In [13]:
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,abd,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.05,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.92,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.51,Cash on Delivery,Processing,552.510
...,...,...,...,...,...,...,...,...,...,...,...
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,Unknown,2,497.01,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.36,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.26,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.42,Bank Transfer,Processing,1410.840

In [14]:
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          0
Quantity           5
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [15]:
df['Quantity'] = df['Quantity'].fillna(0)

In [16]:
df.isnull().sum()

ID                 0
 Customer_Name     0
Order_ID           0
Order_Date         0
Product            0
 Category          0
Quantity           0
Price              5
Payment_Method     0
Status             0
Total             14
dtype: int64

In [18]:
df[df['Price'].isnull()]

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
16,116,Customer_116,ORD-63660,10/30/2025,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
24,124,Customer_124,ORD-46136,5/31/2025,Comics,Books,5,NaN,PayPal,Cancelled,NaN
30,130,Customer_130,ORD-34007,8/15/2025,Tennis Racket,Sports,2,NaN,Bank Transfer,Processing,NaN
56,156,Customer_156,ORD-34679,11/28/2024,Jeans,Clothing,2,NaN,Bank Transfer,Shipped,NaN
83,183,Customer_183,ORD-20916,3/10/2025,Shoes,Clothing,5,NaN,Cash on Delivery,Returned,NaN

In [20]:
df[df['Product'] == 'Microwave']

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
16,116,Customer_116,ORD-63660,10/30/2025,Microwave,Home,4,NaN,Cash on Delivery,Processing,NaN
22,122,Customer_122,ORD-21443,5/16/2025,Microwave,Home,2,556.93,PayPal,Shipped,1113.86
59,159,Customer_159,ORD-98162,7/28/2025,Microwave,Home,3,163.16,PayPal,Shipped,489.48
74,174,Customer_174,ORD-16766,9/20/2025,Microwave,ELECTRONICS,4,187.48,Credit Card,Returned,749.92
88,188,Customer_188,ORD-58590,11/19/2024,Microwave,Home,5,504.05,Cash on Delivery,Shipped,2520.25

In [23]:
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

In [ ]:
df['Price'] = df['Price'].fillna(df['Price'].mean())

df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38.000000,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2,612.992021,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1,389.050000,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5,233.920000,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1,552.510000,Cash on Delivery,Processing,552.510
...,...,...,...,...,...,...,...,...,...,...,...
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,Unknown,2,497.010000,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.280000,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1,111.360000,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5,645.260000,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2,705.420000,Bank Transfer,Processing,1410.840

In [28]:
df[df['Product'] == 'Blender']

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3,38.00,Cash on Delivery,Shipped,114.00
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,0,978.63,Bank Transfer,Processing,NaN
17,117,Customer_117,ORD-72751,2/12/2025,Blender,electronic,-2,10000.00,Cash on Delivery,Processing,-20000.00
27,127,Customer_127,ORD-65482,5/12/2025,Blender,Home,5,336.02,Bank Transfer,Returned,1680.10
54,154,Customer_154,ORD-95990,2/21/2025,Blender,Home,5,789.64,Cash on Delivery,Cancelled,3948.20
62,162,Customer_162,ORD-27743,5/19/2025,Blender,Home,2,155.76,Credit Card,Returned,311.52
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1,160.16,PayPal,Cancelled,160.16
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5,372.28,Credit Card,Shipped,1861.40

In [32]:
df['Quantity'] = pd.to_numeric(df['Quantity'], errors='coerce')

In [36]:
df[df['Quantity'] < 0]

Empty DataFrame
Columns: [ID,  Customer_Name, Order_ID, Order_Date, Product,  Category, Quantity, Price, Payment_Method, Status, Total]
Index: []

In [34]:
df['Quantity'] = df['Quantity'].abs()

In [38]:
df['Total'] = pd.to_numeric(df['Total'], errors='coerce')

In [41]:
df[df['Total'] < 0]

Empty DataFrame
Columns: [ID,  Customer_Name, Order_ID, Order_Date, Product,  Category, Quantity, Price, Payment_Method, Status, Total]
Index: []

In [40]:
df['Total'] = df['Total'].abs()

In [42]:
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')

In [43]:
df['Price'] = df['Price'].abs()

In [56]:
df.isnull().sum()

ID                0
 Customer_Name    0
Order_ID          0
Order_Date        0
Product           0
 Category         0
Quantity          0
Price             0
Payment_Method    0
Status            0
Total             0
dtype: int64

In [55]:
df[df['Quantity'].isnull()]

Empty DataFrame
Columns: [ID,  Customer_Name, Order_ID, Order_Date, Product,  Category, Quantity, Price, Payment_Method, Status, Total]
Index: []

In [48]:
df[df['Product'] == 'Jacket']

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
47,147,Customer_147,ORD-80707,5/1/2025,Jacket,Clothing,4.0,596.15,Cash on Delivery,Shipped,2384.6
57,157,Customer_157,ORD-34407,11/6/2025,Jacket,Clothing,4.0,275.10,Bank Transfer,Processing,1100.4
92,192,Customer_192,ORD-35144,abc,Jacket,Clothing,NaN,203.63,Credit Card,Returned,NaN

In [49]:
df['Quantity'] = df['Quantity'].fillna(df['Quantity'].mean())

In [52]:
df

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3.0,38.000000,Cash on Delivery,Shipped,114.000
1,101,Customer_101,ORD-35783,7/5/2025,Smartphone,Electronics,2.0,612.992021,PayPal,Processing,NaN
2,102,Customer_102,ORD-84355,12/23/2024,Tennis Racket,Sports,1.0,389.050000,PayPal,Delivered,389.050
3,103,Customer_103,ORD-57811,3/19/2025,Science,Books,5.0,233.920000,PayPal,Processing,1169.600
4,104,Customer_104,ORD-93614,10/20/2025,Biography,Books,1.0,552.510000,Cash on Delivery,Processing,552.510
...,...,...,...,...,...,...,...,...,...,...,...
98,198,Customer_198,ORD-14608,7/27/2025,Vacuum,Unknown,2.0,497.010000,Cash on Delivery,Shipped,994.020
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5.0,372.280000,Credit Card,Shipped,1861.400
100,175,Customer_175,ORD-56651,2/24/2025,Headphones,Electronics,1.0,111.360000,Credit Card,Processing,77.952
101,142,Customer_142,ORD-69018,10/30/2025,Shoes,Clothing,5.0,645.260000,Credit Card,Shipped,3226.300
102,146,Customer_146,ORD-32755,7/9/2025,Basketball,electronic,2.0,705.420000,Bank Transfer,Processing,1410.840

In [53]:
df.describe()

               ID    Quantity         Price         Total
count  103.000000  103.000000    103.000000     89.000000
mean   149.640777    2.911765    614.933769   1755.592921
std     28.704326    1.615507    967.141436   2282.277181
min    100.000000    0.000000     38.000000     40.950000
25%    125.500000    2.000000    307.460000    640.024000
50%    149.000000    3.000000    582.130000   1212.600000
75%    174.500000    4.500000    705.420000   2355.920000
max    199.000000    5.000000  10000.000000  20000.000000

In [3]:
df['Total'] = df['Quantity'] * df['Price']

NameError: name 'df' is not defined

In [113]:
### New File
df.to_csv('../files/cleaned_data.csv', index=False)

In [62]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103 entries, 0 to 102
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   ID              103 non-null    int64
 1    Customer_Name  103 non-null    str
 2   Order_ID        103 non-null    str
 3   Order_Date      103 non-null    str
 4   Product         103 non-null    str
 5    Category       103 non-null    str
 6   Quantity        103 non-null    float64
 7   Price           103 non-null    float64
 8   Payment_Method  103 non-null    str
 9   Status          103 non-null    str
 10  Total           103 non-null    float64
dtypes: float64(3), int64(1), str(7)
memory usage: 9.0 KB

In [84]:
df[df.duplicated(keep=False)]

Empty DataFrame
Columns: [ID,  Customer_Name, Order_ID, Order_Date, Product,  Category, Quantity, Price, Payment_Method, Status, Total]
Index: []

In [80]:
df = df.drop_duplicates(keep = 'first')

In [81]:
df.to_csv('../files/cleaned_data.csv', index=False)

In [100]:
df.sort_values(by='Price', ascending=False).head(5)

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,0.0,978.63,Bank Transfer,Processing,0.00
94,194,Customer_194,ORD-69764,2/10/2025,Lamp,Home,5.0,944.54,Cash on Delivery,Returned,4722.70
72,172,Customer_172,ORD-48008,11/18/2024,Comics,Books,2.0,942.76,Bank Transfer,Returned,1885.52
58,158,Customer_158,ORD-35817,4/5/2025,Smartwatch,Electronics,1.0,933.58,Cash on Delivery,Shipped,933.58
90,190,Customer_190,ORD-38469,6/29/2025,Vacuum,Home,1.0,920.37,Bank Transfer,Processing,920.37

In [112]:
Q1 = df['Price'].quantile(0.25)
Q3 = df['Price'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['Price'] < lower_bound) | (df['Price'] > upper_bound)]

print(outliers)

     ID  Customer_Name   Order_ID Order_Date Product  Category  Quantity  \
55  155   Customer_155  ORD-20182   5/1/2025   shoes  Clothing       1.0

    Price Payment_Method    Status  Total
55  40.95         PayPal  Returned  40.95

In [108]:
outlier_products = outliers['Product'].unique()
outlier_products

<StringArray>
[      'Blender',       'Science', 'Tennis Racket',      'Yoga Mat',
     'Biography',        'Vacuum',          'Lamp',         'shoes',
        'Jacket',    'Smartwatch',     'Microwave',        'Comics',
    'Headphones',        'Laptop',    'Smartphone',         'Jeans']
Length: 16, dtype: str

In [110]:
for product in outlier_products:
    mean_price = df[df['Product'] == product]['Price'].median()
    
    df.loc[
        (df['Product'] == product) &
        ((df['Price'] < lower_bound) | (df['Price'] > upper_bound)),
        'Price'
    ] = mean_price

In [111]:
df[df['Product'] == 'Blender']

,ID,Customer_Name,Order_ID,Order_Date,Product,Category,Quantity,Price,Payment_Method,Status,Total
0,100,Customer_100,ORD-41285,11/22/2024,Blender,Home,3.0,345.085,Cash on Delivery,Shipped,114.00
6,106,Customer_106,ORD-25885,2/2/2025,Blender,Home,0.0,345.085,Bank Transfer,Processing,0.00
17,117,Customer_117,ORD-72751,2/12/2025,Blender,electronic,2.0,345.085,Cash on Delivery,Processing,20000.00
27,127,Customer_127,ORD-65482,5/12/2025,Blender,Home,5.0,345.085,Bank Transfer,Returned,1680.10
54,154,Customer_154,ORD-95990,2/21/2025,Blender,Home,5.0,789.640,Cash on Delivery,Cancelled,3948.20
62,162,Customer_162,ORD-27743,5/19/2025,Blender,Home,2.0,345.085,Credit Card,Returned,311.52
97,197,Customer_197,ORD-79139,6/23/2025,Blender,Home,1.0,345.085,PayPal,Cancelled,160.16
99,199,Customer_199,ORD-82922,1/22/2025,Blender,Home,5.0,372.280,Credit Card,Shipped,1861.40